"""Per-ticker best (backbone, approach) selection across multiple ranking metrics.

For each metric in METRICS, picks the row (per ticker) that maximizes that
metric and writes a CSV. The metric that yields the largest combined
LWT + LWT-Warm count is also emitted as a LaTeX table.
"""
from __future__ import annotations
import sys, json
from pathlib import Path
import pandas as pd

DATE = sys.argv[1] if len(sys.argv) > 1 else "2026-05-03"
ROOT = Path(__file__).resolve().parent / "results" / DATE
OUT = ROOT / "_analysis"
ARTICLE = Path("/Users/fteodoro/BRACIS 2026")
CSV_DIR = ARTICLE / "best_per_ticker_by_metric"
CSV_DIR.mkdir(exist_ok=True)

LABEL = {
    "features__raw": "Raw-Feat.",
    "ohlcv__db4": "Db4",
    "ohlcv__learned_wavelet": "LWT-Warm",
    "ohlcv__learned_wavelet_no_warmup": "LWT",
}
KEEP = {"Raw-Feat.", "Db4", "LWT", "LWT-Warm"}

METRICS = [
    "Sharpe", "Sortino", "Calmar", "MDD", "PF", "WinRate",
    "VaR95", "CVaR95", "Acc", "F1", "MCC", "AUC",
]

rows = []
for fmode_dir in (ROOT / "features", ROOT / "ohlcv"):
    if not fmode_dir.exists():
        continue
    fmode = fmode_dir.name
    for tdir in sorted(fmode_dir.iterdir()):
        if not tdir.is_dir():
            continue
        for mdir in sorted(tdir.iterdir()):
            mp = mdir / "metrics.json"
            if not mp.exists():
                continue
            j = json.loads(mp.read_text())
            cond = LABEL.get(f"{fmode}__{j.get('mode')}", None)
            if cond not in KEEP:
                continue
            # Exclude MLP from the per-ticker table to keep the backbone set
            # comparable across all four input conditions.
            if str(j.get("model_name", "")).upper() == "MLP":
                continue
            f = j.get("fin_metrics", {})
            rows.append({
                "Ticker":   tdir.name.replace(".SA", ""),
                "Model":    j.get("model_name"),
                "Approach": cond,
                "Sharpe":   f.get("oos_sharpe"),
                "Sortino":  f.get("oos_sortino"),
                "Calmar":   f.get("oos_calmar"),
                "MDD":      f.get("oos_max_drawdown"),
                "PF":       f.get("oos_profit_factor"),
                "WinRate":  f.get("oos_win_rate"),
                "VaR95":    f.get("oos_var_95"),
                "CVaR95":   f.get("oos_cvar_95"),
                "Acc":      f.get("oos_accuracy"),
                "F1":       f.get("oos_f1_macro"),
                "MCC":      f.get("oos_mcc"),
                "AUC":      f.get("oos_roc_auc_ovr"),
            })

full = pd.DataFrame(rows)


def best_per_ticker(metric: str) -> pd.DataFrame:
    d = full.dropna(subset=[metric]).copy()
    d = d.sort_values(metric, ascending=False)
    d = d.drop_duplicates(subset=["Ticker"], keep="first")
    return d.sort_values("Ticker").reset_index(drop=True)


summary = []
best_dfs = {}
for met in METRICS:
    d = best_per_ticker(met)
    best_dfs[met] = d
    d.to_csv(CSV_DIR / f"best_by_{met}.csv", index=False)
    counts = d["Approach"].value_counts().to_dict()
    summary.append({
        "Metric":       met,
        "Raw-Feat.":    counts.get("Raw-Feat.", 0),
        "Db4":          counts.get("Db4", 0),
        "LWT":          counts.get("LWT", 0),
        "LWT-Warm":     counts.get("LWT-Warm", 0),
        "LWT+LWT-Warm": counts.get("LWT", 0) + counts.get("LWT-Warm", 0),
    })

summary_df = pd.DataFrame(summary).set_index("Metric")
summary_df.to_csv(CSV_DIR / "_summary_lwt_wins.csv")
print("Per-metric Approach distribution among best-per-ticker:")
print(summary_df.to_string())

summary_df["_tiebreak"] = summary_df["LWT-Warm"]
chosen = summary_df.sort_values(
    ["LWT+LWT-Warm", "_tiebreak"], ascending=False
).index[0]
print(f"\nChosen metric for LaTeX table: {chosen} "
      f"(LWT+LWT-Warm = {summary_df.loc[chosen, 'LWT+LWT-Warm']})")

df_best = best_dfs[chosen]


def fmt(x, n=3):
    if pd.isna(x):
        return "--"
    return f"{x:+.{n}f}" if n >= 2 else f"{x:.{n}f}"


def fmt_pct(x):
    return "--" if pd.isna(x) else f"{x*100:.1f}"


lines = [
    r"% AUTO-GENERATED by build_per_run_table.py",
    f"% Ranking metric: {chosen} "
    f"(maximises combined LWT + LWT-Warm wins among 12 candidates)",
    r"\begin{table}[t]\centering\scriptsize\setlength{\tabcolsep}{3pt}",
    r"\caption{Best (backbone, approach) per ticker, ranked by OOS "
    f"{chosen}"
    r". All columns are dimensionless except Acc. and F1 (\%).}"
    r"\label{tab:best-per-ticker}",
    r"\begin{tabular}{lllrrrrrrr}\toprule",
    r"Ticker & Model & Approach & MDD & Sharpe & Sortino "
    r"& Acc. & F1 & AUC \\",
    r"\midrule",
]
for _, r in df_best.iterrows():
    m_disp = r["Model"].replace("_", "-")
    lines.append(
        f"{r['Ticker']} & {m_disp} & {r['Approach']} & "
        f"{fmt(r['MDD'])} & {fmt(r['Sharpe'])} & {fmt(r['Sortino'])} & "
        f"{fmt_pct(r['Acc'])} & {fmt_pct(r['F1'])} & "
        f"{fmt(r['AUC'], 3).lstrip('+')} \\\\"
    )
lines.append(r"\bottomrule\end{tabular}\end{table}")
(OUT / "tab_per_run.tex").write_text("\n".join(lines) + "\n")
print("LaTeX -> tab_per_run.tex")

df_best.to_csv(OUT / "per_run_results.csv", index=False)
print(f"chosen-metric CSV -> per_run_results.csv ({chosen})")
